package dataWriter;

import lombok.SneakyThrows;

import java.io.FileWriter;

/**
 * @author Mohamed_Amr
 * This class is for writing any kind of test-Data (Faker_Generated, Properties file, etc.)
 * that has been used in TCs in an external file in resources directory.
 */
public class TestData_Writer {
    /**
     * Reads test data generated by Faker class in some TCs
     * @param variable_Name the name of the variable I used in TC that stores the fake data
     * @param data the dummy fake data generated by Faker class
     * @return the dummy data to be stored in that variable that will be used in the test_steps
     */
    @SneakyThrows
    public static String write_Generated_Data(String test_Data_File_Path, String variable_Name, String data)
    {
        FileWriter fw = new FileWriter(test_Data_File_Path,true);
        fw.write(variable_Name + ": " + data);
        fw.write("\n");
        fw.flush();
        return data;
    }

}
